stages:
  - build
  - test

.ubuntu_install: &ubuntu_install
  before_script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
    - apt-get install -y --no-install-recommends build-essential cmake libgtest-dev googletest

.ubuntu_build: &ubuntu_build
  stage: build
  script:
    - mkdir build && cd build
    - cmake .. -DBUILD_TESTING=on -DBUILD_EXAMPLES=on
    - make
    - make install
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build

.ubuntu_test: &ubuntu_test
  stage: test
  script:
    - cd build
    - for test in $(find . -executable -type f -name 'test*'); do $test; done

build_ubuntu_latest:
  image: ubuntu:latest
  <<: *ubuntu_install
  <<: *ubuntu_build

test_ubuntu_latest:
  image: ubuntu:latest
  <<: *ubuntu_test
  needs:
    - build_ubuntu_latest

build_ubuntu_focal:
  image: ubuntu:focal
  <<: *ubuntu_install
  <<: *ubuntu_build

test_ubuntu_focal:
  image: ubuntu:focal
  <<: *ubuntu_test
  needs:
    - build_ubuntu_focal

build_ubuntu_bionic:
  image: ubuntu:bionic
  stage: build
  <<: *ubuntu_install
  script:
    - cd /usr/src/googletest
    - cmake .
    - cmake --build . --target install
    - cd $CI_PROJECT_DIR
    - mkdir build && cd build
    - cmake .. -DBUILD_TESTING=on -DBUILD_EXAMPLES=on
    - make
    - make install
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - build

test_ubuntu_bionic:
  image: ubuntu:bionic
  <<: *ubuntu_test
  needs:
    - build_ubuntu_bionic
